import Game from "./Game";
import { connect } from "react-redux";
import { IStore } from "../../types/IStore";
import {
  handleStopGame,
  handleCoordinatesFood,
  increseSpeed,
  handleGameOver,
  handleOnKeyDown,
  handleMoveSnake,
  enlargeSnake,
  checkIfOutOfBorder,
  checkIfCollapsed,
  changeComboActive,
  changeWidthProgress,
  changeComboCounter,
  changeComboSplit,
  handleOpenForm,
  handleFormErrors,
  handleMute,
  handleValidation,
  setNickname,
  handleOpenRecords,
  handleSubmitSend,
  handleShowError,
  handleOpenInstruction,
} from "../../actions/snake";

const mapStateToProps = (state: IStore) => ({
  stopGame: state.snake.stopGame,
  food: state.snake.food,
  speed: state.snake.speed,
  gameOver: state.snake.gameOver,
  direction: state.snake.direction,
  snakeDots: state.snake.snakeDots,
  comboActive: state.snake.comboActive,
  comboCounter: state.snake.comboCounter,
  widthProgress: state.snake.widthProgress,
  comboSplit: state.snake.comboSplit,
  openForm: state.snake.openForm,
  errors: state.snake.errors,
  mute: state.snake.mute,
  nickname: state.snake.nickname,
  openRecords: state.snake.openRecords,
  submitSend: state.snake.submitSend,
  showError: state.snake.showError,
  openInstruction: state.snake.openInstruction,
});

export default connect(mapStateToProps, {
  handleStopGame,
  handleCoordinatesFood,
  increseSpeed,
  handleGameOver,
  handleOnKeyDown,
  handleMoveSnake,
  enlargeSnake,
  checkIfOutOfBorder,
  checkIfCollapsed,
  changeComboActive,
  changeWidthProgress,
  changeComboCounter,
  handleFormErrors,
  handleOpenForm,
  changeComboSplit,
  handleMute,
  handleValidation,
  setNickname,
  handleOpenRecords,
  handleSubmitSend,
  handleShowError,
  handleOpenInstruction,
})(Game as any);
